language: node_js
node_js:
  - 0.6

branches:
  only:
    - new_api_layout
    - tnac_api_kanso
    - master

before_script:
  - sh -c "cd tnac_api; ../node_modules/.bin/kanso install; ../node_modules/.bin/kanso push default; ../node_modules/.bin/kanso upload data default"
